config/routes.rb
Arcademovelist::Application.routes.draw do
  resources :games do
    get :inline_update
  end
  resources :characters do
    post :sort, on: :collection
      get :inline_update
  end
  resources :moves do
    post :sort, on: :collection
      get :inline_update
  end
  resources :tabs do
    post :sort, on: :collection
  end
  resources :notes do
    post :sort, on: :collection
      get :inline_update
  end
  resources :setups do
    post :sort, on: :collection
      get :inline_update
  end
  resources :fatalities do
    post :sort, on: :collection
      get :inline_update
  end
  resources :builds

  root "games#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
  acts_as_list
  belongs_to :tab

  EDIT_FIELDS = [{column_name: :description , column_type: 'text_field'}]


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:sort]
  before_action :set_note, only: [:show, :edit, :update, :inline_update, :destroy]

  def index
    @notes = Note.all
  end

  def inline_update
    
    @note.send("#{params[:field]}=",params[:value])
    @note.save
    render json: {success: true}

  end

  def new
    @note = Note.new(note_params)
  end

  def sort
    param = params[:tab_id]

    @notes = Note.where("tab_id = '#{param}'")

    @notes.each do |note|
      note.position = params['note'].index(note.id.to_s) + 1
      note.save
    end
    render :nothing => true
  end

  def show

  end


  def edit
  end

  def create
    @note = Note.create(note_params)
    redirect_to @note.tab.tabable
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note.tab.tabable, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.tab.tabable, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    if @note.destroy
      flash[:success] = "Note was deleted."
    else
      flash[:error] = "Note could not be deleted."
    end
    redirect_to @note.tab.tabable
  end

  private

  def set_note
    @note = Note.find(params[:id]||params[:note_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def note_params
    params.require(:note).permit(:tab_id, :description, :position)
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for @note do |f| %>
  <%= f.hidden_field :tab_id %>
  <%= f.text_area :description, placeholder: 'Description' %>
  <%= f.submit "Submit" %>
<% end %>

app/views/notes/_note.html.erb
<li id="note_<%= object.id %>" id='note_item' data-url="<%= object.tab_id %>">
  <table cellpadding="0" width="100%">
    <tbody>
      <tr>
        <td valign="center" class="handle" align="center" width="15%"><%= link_to "Edit", edit_note_path(object.id) %> <%= link_to "Delete", note_path(object.id), method: :delete, data: {confirm: "Sure?" } %></td>
        <td valign="center" align="left">
          <h5><%= object.description %></h5>
        </td>
      </tr>
    </tbody>
  </table>
</li>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', @note.tab.tabable %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

 nothing here

app/views/notes/new.html.erb
<h1>New note for <%= @note.tab.tabable.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', @note.tab.tabable %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong><%= @note.description %></strong>
</p>
<%= link_to 'Edit', edit_note_path(@note) %>
<%= link_to 'Back', @note.tab.tabable %>