config/routes.rb
Arcademovelist::Application.routes.draw do
  resources :games do
    get :inline_update
  end
  resources :characters do
    post :sort, on: :collection
      get :inline_update
  end
  resources :moves do
    post :sort, on: :collection
      get :inline_update
  end
  resources :tabs do
    post :sort, on: :collection
  end
  resources :notes do
    post :sort, on: :collection
      get :inline_update
  end
  resources :setups do
    post :sort, on: :collection
      get :inline_update
  end
  resources :fatalities do
    post :sort, on: :collection
      get :inline_update
  end
  resources :builds

  root "games#index"

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :tabs, as: :tabable, :order => 'position ASC', dependent: :destroy
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :inline_update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.order('games.name ASC')
    @game = Game.new
   end

  # GET /games/1
  # GET /games/1.json
  def show
    @character = Character.new
    @setup = Setup.new
    @tab = Tab.new
    @note = Note.new
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def inline_update
    
    @game.send("#{params[:field]}=",params[:value])
    @game.save
    render json: {success: true}

  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id]||params[:game_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:name, :platform, :genre, :developer, :description, :year)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game, method: :post, url: games_path)  do |f| %>
  <li id="new-data-fields" >
    <div class="panel panel-default">
      <div class="panel-heading">
        <table id="interesting-content" width="100%">
          <tr>
            <td valign="center" align="left" width="85%">
              <h1>
                <%= f.text_field :name, placeholder: 'Game name', required: true %>
              </h1>
            </div>
          </td>
          <td>
          </td>
          <td >
            <div class="btn">
              <%= button_tag(type: 'submit', class: "btn btn-primary", id:"save-button") do %>
                Save
                <% end %>
            </div>
          </td>
          <td width="5%">
          </td>
        </tr>
      </table>
      <div id="collapse_new" class="panel-collapse">
        <div class="panel-body">
          <h4>
            Developer: <%= f.text_field :developer, placeholder: 'Taito' %><br>
            Platform: <%= f.text_field :platform, placeholder: 'G-Net' %><br>
            Genre: <%= f.text_field :genre, placeholder: 'Shooter' %><br>
            Description: <%= f.text_field :description, placeholder: '1p bullet-hell' %><br>
            Year: <%= f.text_field :year, placeholder: '1998' %><br>
          </h4>
        </div>
      </div>
    </div>
  </li>
<% end %>

app/views/games/_game.html.erb
<li <% game.attributes.each_pair do |name, value| %> 
        data-<%= name.downcase %>='<%= value.try(:downcase) %>' 
        <% end %> >
  <div class="panel panel-default">
    <div class="panel-heading">
      <table id="interesting-content" width="100%">
        <tr>
          <td valign="center" align="left" width="85%" data-url="<%=url_for game%>" class="">
            <h1>
              <input data-submiturl="<%= game_inline_update_path(game, field: :name) %>" type="text" class="editField" value="<%= game.name %>" readonly>
            </h1>
          </div>
        </td>
        <td>
          <% game.attributes.each_pair do |name, value| %>
            <span style='display:none' 
                        data-aux='<%= value.try(:downcase) %>' 
                        class='aux'>
              <%= value %>
            </span>
          <% end %>
        </td>
        <td >
          <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=game.id%>"></a>
        </td>
        <td width="5%">
        </td>
      </tr>
    </table>
    <div id="collapse<%=game.id%>" class="panel-collapse collapse">
      <div class="panel-body" data-fields="true">
        <h4>Year: <input data-submiturl="<%= game_inline_update_path(game, field: :year) %>" type="text" class="editField" value="<%= game.year %>" readonly><br>
          Genre: <input data-submiturl="<%= game_inline_update_path(game, field: :genre) %>" type="text" class="editField" value="<%= game.genre %>" readonly><br>
          Platform: <input data-submiturl="<%= game_inline_update_path(game, field: :platform) %>" type="text" class="editField" value="<%= game.platform %>" readonly><br>
          Developer: <input data-submiturl="<%= game_inline_update_path(game, field: :developer) %>" type="text" class="editField" value="<%= game.developer %>" readonly>
        </h4>
        <div id="delete-button" data-url="true" delete-button="true" >
          <%= link_to 'Destroy', game, method: :delete, class: "btn btn-primary", data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  </div>
</div>
</li>

app/views/games/edit.html.erb
<h2>Editing game</h2>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', root_path %>

app/views/games/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid" id="tabs">
    <ul class="navbar-left">
      <ul class="breadcrumb list-inline">
        <li id="topnav-bcrumb" class="active">Games</li>
        <li id="topnav-bcrumb">
          <small>
            <input id="search_field" name="search_field" placeholder="Search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search'" >
          </small>
        </li>
      </ul>
    </ul>
    <ul class="navbar-right">
      <div id="edit-button" class='row text-center'>
        <a class="btn newBtn" >New</a>
        <a class="btn editBtn">Edit</a>
      </div>
    </ul>
  </div>
</nav>
<div id="new-data-fields_" class="" readonly>
  <ul>
      <%= render partial: 'form' %>
    </ul>
</div>
<div id="existing-data-fields_" class="">
  <form role="form">
    <ul>
      <% @games.each do |game| %>
        <%= render partial: 'game', locals: {game: game}  %>
      <% end %>
    </ul>
  </form>
</div>

app/views/games/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="height: 65px;" >
  <div class="container-fluid" id="tabs">
    <ul class="navbar-left">
      <ul class="breadcrumb list-inline">
        <li id="topnav-bcrumb" data-url="<%= url_for root_path %>">Games</li>
        <li id="topnav-bcrumb" class="active"><%= @game.name %></li>
      </ul>
    </ul>
    <ul class="navbar-left">
      <ul id="my-pills" class="nav nav-pills" role="tablist">
        <% @game.tabs.each do |tab| %>
          <%= render partial: 'tabs/tab', locals: {tab: tab} %>
        <% end %>
        <li><%= link_to '+', new_tab_path(tab: {tabable_id: @game.id, tabable_type: @game.class.name}) %></li>
      </ul>
    </ul>
    <ul class="navbar-right">
      <div id="edit-button" class='row text-center'>
        <a class="btn newBtn" >New</a>
        <a class="btn editBtn">Edit</a>
      </div>
    </ul>
  </div>
</nav>
<div id="rows" class="tab-content">
  <% @game.tabs.each do |tab| %>
    <%= render partial: 'tabs/tab_body', locals: {tab: tab} %>
  <% end %>
</div>