config/routes.rb
Arcademovelist::Application.routes.draw do
  resources :games do
    get :inline_update
  end
  resources :characters do
    post :sort, on: :collection
      get :inline_update
  end
  resources :moves do
    post :sort, on: :collection
      get :inline_update
  end
  resources :tabs do
    post :sort, on: :collection
  end
  resources :notes do
    post :sort, on: :collection
      get :inline_update
  end
  resources :setups do
    post :sort, on: :collection
      get :inline_update
  end
  resources :fatalities do
    post :sort, on: :collection
      get :inline_update
  end
  resources :builds

  root "games#index"

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :tab
  has_many :tabs, as: :tabable, :order => 'position ASC', dependent: :destroy

  EDIT_FIELDS = [{column_name: :name , column_type: 'text_field'},
                 {column_name: :description , column_type: 'text_field'}]

  def initialize(character_params = {})

    super character_params

    if self.tab != nil #<!--this is what is blocking characters/builds errors -->

      if !self.tab.builds.empty?
        self.tab.builds.each{|build| self.tabs.build(tab_type: build.name, position: build.position)}
      end
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  before_action :set_character, only: [:show, :edit, :inline_update, :update, :destroy]

  def index
    @characters = Character.order('characters.name ASC')
  end

  def new
    @character = Character.new(character_params)
  end

  def inline_update
    
    @character.send("#{params[:field]}=",params[:value])
    @character.save
    render json: {success: true}

  end

  def show
    
    @setup = Setup.new
    @tab = Tab.new
    @note = Note.new
  end

  def edit
  end

  def create
    @character = Character.create(character_params)
    redirect_to @character.tab.tabable
  end

  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character.tab.tabable, notice: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    if @character.destroy
      flash[:success] = "Character was deleted."
    else
      flash[:error] = "Character could not be deleted."
    end
    redirect_to @character.tab.tabable
  end

  private

  def set_character
    @character = Character.find(params[:id]||params[:character_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def character_params
    params.require(:character).permit(:tab_id, :name, :description, :position)
  end

end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_character.html.erb
<li id="character_<%= object.id %>" id='character_item'>
  <div class="panel panel-default">
    <div class="panel-heading">
      <table id="interesting-content" width="100%">
        <tr>
          <td valign="center" align="left" width="85%" data-url="<%=url_for object%>" class="">
            <h1>
              <input data-submiturl="<%= character_inline_update_path(object, field: :name) %>" type="text" class="editField" value="<%= object.name %>" readonly>
            </h1>
          </div>
        </td>
        <td>
          <span></span>
        </td>
        <td >
          <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=object.id%>"></a>
        </td>
        <td width="5%">
        </td>
      </tr>
    </table>
    <div id="collapse<%=object.id%>" class="panel-collapse collapse">
      <div class="panel-body" data-fields="true">
        <h4>Description: <input data-submiturl="<%= character_inline_update_path(object, field: :description) %>" type="text" class="editField" value="<%= object.description %>" readonly>
        </h4>
        <div id="delete-button" data-url="true">
          <%= link_to 'Destroy', object, method: :delete, class: "btn btn-primary", data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  </div>
</div>
</li>

app/views/characters/_form.html.erb
<%= form_for(@character, method: :post, url: characters_path) do |f| %>
  <%= f.hidden_field :tab_id, value: object.id  %>
  <%= f.hidden_field :position %><br>
  <li id="new-object-form_<%=object.id%>" >
    <div class="panel panel-default">
      <div class="panel-heading">
        <table id="interesting-content" width="100%">
          <tr>
            <td valign="center" align="left" width="85%">
              <h1>
              <%= f.text_field :name, placeholder: 'Name' %>
            </h1>
          </div>
        </td>
        <td>
          <span></span>
        </td>
        <td >
         <div class="btn">
              <%= button_tag(type: 'submit', class: "btn btn-primary", id:"save-button") do %>
                Save
                <% end %>
            </div>
        </td>
        <td width="5%">
        </td>
      </tr>
    </table>
    <div id="collapse<%=object.id%>" class="panel-collapse">
      <div class="panel-body" data-fields="true">
        <h4>
        	<%= f.text_field :description, placeholder: 'Description' %>
        </h4>
        <div>
          
        </div>
      </div>
    </div>
  </div>
</div>
</li>
<% end %>

app/views/characters/_new.html.erb
<h1>New Character for <%= @character.tab.tabable.name %></h1>
<%= render 'form' %>
<%= link_to 'Back', @character.tab.tabable %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>
<%= render 'form' %>
<%= link_to 'Show', @character %> |
<%= link_to 'Back', @character.tab.tabable %>

app/views/characters/new.html.erb
<h1>New Character for <%= @character.tab.tabable.name %></h1>
<%= render 'form' %>
<%= link_to 'Back', @character.tab.tabable %>

app/views/characters/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="height: 5em;" >
  <div class="container-fluid" id="tabs">
    <ul class="navbar-left">
      <ul class="breadcrumb list-inline">
        <li id="topnav-bcrumb" data-url="<%= url_for root_path %>">Games</li>
        <li id="topnav-bcrumb" data-url="<%= url_for @character.tab.tabable %>"><%= @character.tab.tabable.name %></li>
        <li id="topnav-bcrumb" class="active"><%= @character.name %></li>
      </ul>
    </ul>
    <ul class="navbar-left">
      <ul id="my-pills" class="nav nav-pills" role="tablist" >
        <% @character.tabs.each do |tab| %>
          <%= render partial: 'tabs/tab', locals: {tab: tab} %>
        <% end %>
        <li><%= link_to '+', new_tab_path(tab: {tabable_id: @character.id, tabable_type: @character.class.name}) %></li>
      </ul>
    </ul>
    <ul class="navbar-right">
      <div id="edit-button" class='row text-center'>
        <a class="btn editBtn">Edit</a>
      </div>
    </ul>
    </div>
  </nav>
  <div id="rows" class="tab-content">
    <% @character.tabs.each do |tab| %>
      <%= render partial: 'tabs/tab_body', locals: {tab: tab} %>
    <% end %>
  </div>