config/routes.rb
Arcademovelist::Application.routes.draw do
  resources :games do
    get :inline_update
  end
  resources :characters do
    post :sort, on: :collection
      get :inline_update
  end
  resources :moves do
    post :sort, on: :collection
      get :inline_update
  end
  resources :tabs do
    post :sort, on: :collection
  end
  resources :notes do
    post :sort, on: :collection
      get :inline_update
  end
  resources :setups do
    post :sort, on: :collection
      get :inline_update
  end
  resources :fatalities do
    post :sort, on: :collection
      get :inline_update
  end
  resources :builds

  root "games#index"

end

app/models/fatality.rb
class Fatality < ActiveRecord::Base
  acts_as_list
  belongs_to :tab

  EDIT_FIELDS = [{column_name: :name , column_type: 'text_field'},
                 {column_name: :description , column_type: 'text_field'},
                 {column_name: :position , column_type: 'number_field'}]

end

app/controllers/fatalities_controller.rb
class FatalitiesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:sort]
  before_action :set_fatality, only: [:show, :edit, :inline_update, :update, :destroy]

  def index
    @fatalitys = Fatality.all
  end

  def inline_update
    
    @fatality.send("#{params[:field]}=",params[:value])
    @fatality.save
    render json: {success: true}

  end

  def sort
    param = params[:tab_id]

    @fatalities = Fatality.where("tab_id = '#{param}'")

    @fatalities.each do |fatality|
      fatality.position = params['fatality'].index(fatality.id.to_s) + 1
      fatality.save
    end
    render :nothing => true
  end

  def new
    @fatality = Fatality.new(fatality_params)
  end

  def show

  end


  def edit
  end

  # POST /fatalitys
  # POST /fatalitys.json
  def create
    @fatality = Fatality.create(fatality_params)
    redirect_to @fatality.tab.tabable
  end

  # PATCH/PUT /fatalitys/1
  # PATCH/PUT /fatalitys/1.json
  def update
    respond_to do |format|
      if @fatality.update(fatality_params)
        format.html { redirect_to @fatality.tab.tabable, notice: 'fatality was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fatality.tab.tabable, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    if @fatality.destroy
      flash[:success] = "fatality was deleted."
    else
      flash[:error] = "fatality could not be deleted."
    end
    redirect_to @fatality.tab.tabable
  end

  private

  def set_fatality
    @fatality = Fatality.find(params[:id]||params[:character_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def fatality_params
    params.require(:fatality).permit(:tab_id, :name, :description, :position)
  end

end

app/helpers/fatalities_helper.rb
module FatalitiesHelper
end

app/views/fatalities/_fatality.html.erb
<li id="fatality_<%= object.id %>" id='fatality_item' data-url="<%= object.tab_id %>">
  <table id="interesting-content" width="100%">
    <tbody>
      <tr>
        <td valign="center" class="handle" align="center" width="15%"><strong><%= object.name %></strong><br>
          <%= link_to "Edit", edit_fatality_path(object.id) %> <%= link_to "Delete", fatality_path(object.id), method: :delete, data: {confirm: "Sure?" } %></td>
        <td valign="center" align="left">
          <h1><%= object.description %></h1>
        </td>
      </tr>
    </tbody>
  </table>
</li>

app/views/fatalities/_form.html.erb
<%= form_for @fatality do |f| %>
  <%= f.hidden_field :tab_id %>
  <%= f.text_field :name, placeholder: 'Name' %><br>
  <%= f.text_field :description, placeholder: 'Description' %><br>
  <%= f.number_field :position %><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/fatalities/edit.html.erb
<h1>Editing fatality for @fatality.tab.tabable</h1>

<%= render 'form' %>

<%= link_to 'Show', @fatality %> |
<%= link_to 'Back', @fatality.tab.tabable %>

app/views/fatalities/index.html.erb
<h1>Listing fatalities</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Game</th>
      <th>Character</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @fatalities.each do |fatality| %>
      <tr>
        <td><%= fatality.name %></td>
        <td><%= fatality.description %></td>
        <td><%= fatality.game %></td>
        <td><%= fatality.character %></td>
        <td><%= link_to 'Show', fatality %></td>
        <td><%= link_to 'Edit', edit_fatality_path(fatality) %></td>
        <td><%= link_to 'Destroy', fatality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New fatality', new_fatality_path %>

app/views/fatalities/new.html.erb
<h1>New fatality for <%= @fatality.tab.tabable.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', @fatality.tab.tabable %>

app/views/fatalities/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <h1><%= @fatality.name %></h1>
  <strong><%= @fatality.description %></strong>
</p>
<%= link_to 'Edit', edit_fatality_path(@fatality) %>
<%= link_to 'Back', @fatality.tab.tabable %>